### ISSUE TITLE
Please add method allow Http Proxy with Authentication

### ISSUE THREAD

**Issue by tungphan899** [OmarTariq612/http2socks#1]
Verry nice project, but can you please add Authentication to Http Proxy ?

**Comment by OmarTariq612** [comment]
Done, you can now use http basic auth and provide a username and a password using this command:
`./http2socks --socks 192.168.1.10:1080 --cred user:pass`
replace `192.168.1.10:1080` with your socks server address.
but this method of authentication is not secure as any one in the middle can see the encoded username and password in clear text.

**Comment by tungphan899** [comment]
Verry helpful. You are the best.
By the way, i can see you have a repository named socks-server, can you please anwser me, how you can make the DNS go through socks5 ? Sorry for my bad english.
Examples : I have a socks5 : 115.115.115.115:3208
But when i use that socks5, and try check my ip address, website show 115.115.115.115, its right, but website show my DNS record is my real ip address 's DNS (without proxying). 
How can you make the socks5 (115.115.115.115:3208) use its (115.115.115.115) DNS record ?

**Comment by OmarTariq612** [comment]
The spec of the socks version 5 protocol has support for 3 types of addresses (ipv4 and ipv6 addresses and domain names) but it's the client's decision whether to resolve DNS locally or proxy DNS by specifying the domain name inside the request to the socks server.
ex: in firefox you can find an option for whether you'd like to resolve DNS locally or proxy DNS through the socks server:
![b66c7085-63d9-4985-82b1-131d085e0cba](https://user-images.githubusercontent.com/65053572/192503049-8de0d17e-d72c-44bc-ba31-9d01e5422951.jpg)
another example using curl:
![Screenshot from 2022-09-27 12-34-19](https://user-images.githubusercontent.com/65053572/192503598-88fd4f78-155e-45b8-bed5-b73eb3e222af.png)
the difference between --socks5 and --socks5h is that --socks5 resolves DNS locally but --socks5h sends the domain name as it is to the socks server.

socks 5 spec (rfc 1928): https://www.rfc-editor.org/rfc/rfc1928
